[package]
name = "iron"
version = "0.1.0"
edition = "2021"

[dependencies]
image = "0.23"
glam = "0.20.3"
env_logger = "0.9.0"
log = "0.4.16"
clap = { version = "4.1.4", features = ["derive"] }
euroc = "0.1.0"
anyhow = "1.0"
raylib = "3.7.0"


[profile.dev]
opt-level = 1
